   version: 0.2

   phases:
     install:
       runtime-versions:
         nodejs: latest
     pre_build:
       commands:
         - npm install
     build:
       commands:
         - npm run build
     post_build:
       commands:
         - aws s3 sync build/ s3://
devtmehosting --delete
         - aws cloudfront create-invalidation --distribution-id E2R1H3U4I8TJEP --paths "/*"

   artifacts:
     base-directory: build
     files:
       - '**/*'